In [1]:
import pandas as pd

In [114]:
df = pd.read_csv('data/coverage16_v3.csv')

In [115]:
df

,id,district,pop_16,dpt16,bcg16,mea16,polio16,ipv16,pcv16,hpv16,dpt_droprate16,pentapcv_gap16,score16
0,1,ABIM,"121,540",164,91,170,157,81,155,7,-17,9,89
1,2,ADJUMANI,"229,324",111,91,102,106,44,105,4,0,7,100
2,3,AGAGO,"236,066",120,91,105,204,49,120,0,-8,1,89
3,4,ALEBTONG,"240,462",87,78,73,88,43,83,2,8,4,89
4,5,AMOLATAR,"157,953",106,87,87,106,51,98,2,8,8,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,108,SOROTI,"318,590",97,86,81,94,30,93,1,0,5,89
108,109,TORORO,"544,320",103,101,96,96,30,97,2,2,6,89
109,110,WAKISO,"2,269,778",81,62,79,77,33,76,1,6,5,67
110,111,YUMBE,"539,619",71,45,68,71,41,69,3,3,2,67
111,112,ZOMBO,"254,209",105,101,101,92,51,89,1,7,16,67

In [116]:
df.columns

Index(['id', 'district', 'pop_16', 'dpt16', 'bcg16', 'mea16', 'polio16',
       'ipv16', 'pcv16', 'hpv16', 'dpt_droprate16', 'pentapcv_gap16',
       'score16'],
      dtype='object')

In [9]:
ele = pd.read_csv('data/ele21.csv')

In [10]:
ele

,District,Reg. Voters,AMURIAT OBOI PATRICK,KABULETA KIIZA JOSEPH,KALEMBE NANCY LINDA,KATUMBA JOHN,KYAGULANYI SSENTAMU ROBERT,MAO NORBERT,MAYAMBALA WILLY,MUGISHA MUNTU GREGG,MWESIGYE FRED,TUMUKUNDE HENRY KAKURUGU,YOWERI MUSEVENI TIBUHABUR WA KAGUTA,Valid Votes
0,001 APAC,88834,1483\n2.84%,277\n0.53%,263\n0.50%,246\n0.47%,16485\n31.55%,310\n0.59%,117\n0.22%,326\n0.62%,300\n0.57%,537\n1.03%,31908\n61.07%,52252
1,002 ARUA,65738,491\n1.45%,180\n0.53%,207\n0.61%,111\n0.33%,7966\n23.57%,240\n0.71%,85\n0.25%,271\n0.80%,197\n0.58%,232\n0.69%,23824\n70.48%,33804
2,003 BUNDIBUGYO,113472,227\n0.32%,119\n0.17%,153\n0.21%,148\n0.21%,18076\n25.18%,92\n0.13%,36\n0.05%,185\n0.26%,100\n0.14%,229\n0.32%,52408\n73.02%,71773
3,004 BUSHENYI,140415,2029\n2.39%,295\n0.35%,337\n0.40%,866\n1.02%,10937\n12.91%,138\n0.16%,51\n0.06%,2841\n3.35%,141\n0.17%,534\n0.63%,66572\n78.56%,84741
4,005 GULU,45342,1165\n5.87%,255\n1.29%,171\n0.86%,119\n0.60%,3023\n15.24%,4011\n20.22%,598\n3.01%,208\n1.05%,117\n0.59%,175\n0.88%,9997\n50.39%,19839
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,142 MBALE CITY,147774,2037\n2.70%,117\n0.16%,249\n0.33%,239\n0.32%,42267\n56.08%,173\n0.23%,48\n0.06%,147\n0.20%,193\n0.26%,182\n0.24%,29717\n39.43%,75369
142,143 TEREGO,95118,1344\n2.78%,580\n1.20%,484\n1.00%,965\n2.00%,16720\n34.57%,705\n1.46%,243\n0.50%,1329\n2.75%,458\n0.95%,814\n1.68%,24718\n51.11%,48360
143,144 LIRA CITY,111772,1523\n2.92%,453\n0.87%,496\n0.95%,326\n0.62%,17495\n33.51%,578\n1.11%,108\n0.21%,359\n0.69%,219\n0.42%,386\n0.74%,30271\n57.97%,52214
144,145 HOIMA CITY,62018,292\n0.84%,2285\n6.60%,69\n0.20%,109\n0.31%,11662\n33.70%,51\n0.15%,14\n0.04%,261\n0.75%,32\n0.09%,83\n0.24%,19751\n57.07%,34609
145,146 SOROTI CITY,56019,13200\n43.46%,158\n0.52%,123\n0.40%,79\n0.26%,3984\n13.12%,95\n0.31%,94\n0.31%,115\n0.38%,44\n0.14%,452\n1.49%,12031\n39.61%,30375

In [45]:
cats = ele.select_dtypes(exclude='int')

In [57]:
for each in cats.columns:
    ele[each] = cats[each].str.split('\\n', expand=True)[0]

In [58]:
ele

,District,Reg. Voters,AMURIAT OBOI PATRICK,KABULETA KIIZA JOSEPH,KALEMBE NANCY LINDA,KATUMBA JOHN,KYAGULANYI SSENTAMU ROBERT,MAO NORBERT,MAYAMBALA WILLY,MUGISHA MUNTU GREGG,MWESIGYE FRED,TUMUKUNDE HENRY KAKURUGU,YOWERI MUSEVENI TIBUHABUR WA KAGUTA,Valid Votes
0,001 APAC,88834,1483,277,263,246,16485,310,117,326,300,537,31908,52252
1,002 ARUA,65738,491,180,207,111,7966,240,85,271,197,232,23824,33804
2,003 BUNDIBUGYO,113472,227,119,153,148,18076,92,36,185,100,229,52408,71773
3,004 BUSHENYI,140415,2029,295,337,866,10937,138,51,2841,141,534,66572,84741
4,005 GULU,45342,1165,255,171,119,3023,4011,598,208,117,175,9997,19839
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,142 MBALE CITY,147774,2037,117,249,239,42267,173,48,147,193,182,29717,75369
142,143 TEREGO,95118,1344,580,484,965,16720,705,243,1329,458,814,24718,48360
143,144 LIRA CITY,111772,1523,453,496,326,17495,578,108,359,219,386,30271,52214
144,145 HOIMA CITY,62018,292,2285,69,109,11662,51,14,261,32,83,19751,34609
145,146 SOROTI CITY,56019,13200,158,123,79,3984,95,94,115,44,452,12031,30375

In [62]:
ele['District'] = ele['District'].str.split(" ", 1, expand=True)[1]

In [63]:
ele

,District,Reg. Voters,AMURIAT OBOI PATRICK,KABULETA KIIZA JOSEPH,KALEMBE NANCY LINDA,KATUMBA JOHN,KYAGULANYI SSENTAMU ROBERT,MAO NORBERT,MAYAMBALA WILLY,MUGISHA MUNTU GREGG,MWESIGYE FRED,TUMUKUNDE HENRY KAKURUGU,YOWERI MUSEVENI TIBUHABUR WA KAGUTA,Valid Votes
0,APAC,88834,1483,277,263,246,16485,310,117,326,300,537,31908,52252
1,ARUA,65738,491,180,207,111,7966,240,85,271,197,232,23824,33804
2,BUNDIBUGYO,113472,227,119,153,148,18076,92,36,185,100,229,52408,71773
3,BUSHENYI,140415,2029,295,337,866,10937,138,51,2841,141,534,66572,84741
4,GULU,45342,1165,255,171,119,3023,4011,598,208,117,175,9997,19839
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,MBALE CITY,147774,2037,117,249,239,42267,173,48,147,193,182,29717,75369
142,TEREGO,95118,1344,580,484,965,16720,705,243,1329,458,814,24718,48360
143,LIRA CITY,111772,1523,453,496,326,17495,578,108,359,219,386,30271,52214
144,HOIMA CITY,62018,292,2285,69,109,11662,51,14,261,32,83,19751,34609
145,SOROTI CITY,56019,13200,158,123,79,3984,95,94,115,44,452,12031,30375

In [99]:
ele = ele.sort_values(by='District')

In [101]:
n = ele['District'].isin(df['district'])

In [102]:
n.value_counts()

True     112
False     34
Name: District, dtype: int64

In [67]:
import numpy as np

In [79]:
np.where(ele['District']==(df['district']), ele['district'])

ValueError: Can only compare identically-labeled Series objects

In [95]:
for each in df['district']:
#     if each in ele['District']:
    print (each)

ABIM
ADJUMANI
AGAGO
ALEBTONG
AMOLATAR
AMUDAT
AMURIA
AMURU
APAC
ARUA
BUDAKA
BUDUDA
BUGIRI
BUHWEJU
BUIKWE
BUKEDEA
BUKOMANSIMBI
BUKWO
BULAMBULI
BULIISA
BUNDIBUGYO
BUSHENYI
BUSIA
BUTALEJA
BUTAMBALA
BUVUMA
BUYENDE
DOKOLO
GOMBA
GULU
HOIMA
IBANDA
IGANGA
ISINGIRO
JINJA
KAABONG
KABALE
KABAROLE
KABERAMAIDO
KALANGALA
KALIRO
KALUNGU
KAMPALA
KAMULI
KAMWENGE
KANUNGU
KAPCHORWA
KASESE
KATAKWI
KAYUNGA
KIBAALE
KIBOGA
KIBUKU
KIRUHURA
KIRYANDONGO
KISORO
KITGUM
KOBOKO
KOLE
KOTIDO
KUMI
KWEEN
KYANKWANZI
KYEGEGWA
KYENJOJO
LAMWO
LIRA
LUUKA
LUWERO
LWENGO
LYANTONDE
MANAFWA
MARACHA
MASAKA
MASINDI
MAYUGE
MBALE
MBARARA
MITOOMA
MITYANA
MOROTO
MOYO
MPIGI
MUBENDE
MUKONO
NAKAPIRIPIRIT
NAKASEKE
NAKASONGOLA
NAMAYINGO
NAMUTUMBA
NAPAK
NEBBI
NGORA
NTOROKO
NTUNGAMO
NWOYA
OTUKE
OYAM
PADER
PALLISA
RAKAI
RUBIRIZI
RUKUNGIRI
SSEMBABULE
SERERE
SHEEMA
SIRONKO
SOROTI
TORORO
WAKISO
YUMBE
ZOMBO

In [104]:
df.rename(columns = {'district':'District'}, inplace = True)

In [105]:
df

,id,District,pop_16,dpt16,bcg16,mea16,polio16,ipv16,pcv16,hpv16,dpt_droprate16,pentapcv_gap16,score16
0,1,ABIM,"121,540",164,91,170,157,81,155,7,-17,9,89
1,2,ADJUMANI,"229,324",111,91,102,106,44,105,4,0,7,100
2,3,AGAGO,"236,066",120,91,105,204,49,120,0,-8,1,89
3,4,ALEBTONG,"240,462",87,78,73,88,43,83,2,8,4,89
4,5,AMOLATAR,"157,953",106,87,87,106,51,98,2,8,8,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,108,SOROTI,"318,590",97,86,81,94,30,93,1,0,5,89
108,109,TORORO,"544,320",103,101,96,96,30,97,2,2,6,89
109,110,WAKISO,"2,269,778",81,62,79,77,33,76,1,6,5,67
110,111,YUMBE,"539,619",71,45,68,71,41,69,3,3,2,67
111,112,ZOMBO,"254,209",105,101,101,92,51,89,1,7,16,67

In [107]:
np.where((ele['District'] == df['District']), ele['District'], np.nan)

ValueError: Can only compare identically-labeled Series objects

In [108]:
ele['District']==df['District']

ValueError: Can only compare identically-labeled Series objects

In [112]:
x = df.merge(ele, left_on='District', right_on='District', how='left')

In [113]:
x.columns

Index(['id', 'District', 'pop_16', 'dpt16', 'bcg16', 'mea16', 'polio16',
       'ipv16', 'pcv16', 'hpv16', 'dpt_droprate16', 'pentapcv_gap16',
       'score16', 'Reg. Voters', 'AMURIAT OBOI PATRICK',
       'KABULETA KIIZA JOSEPH', 'KALEMBE NANCY LINDA', 'KATUMBA JOHN',
       'KYAGULANYI SSENTAMU ROBERT', 'MAO NORBERT', 'MAYAMBALA WILLY',
       'MUGISHA MUNTU GREGG', 'MWESIGYE FRED', 'TUMUKUNDE HENRY KAKURUGU',
       'YOWERI MUSEVENI TIBUHABUR WA KAGUTA', 'Valid Votes'],
      dtype='object')

In [121]:
x = x.drop(['id', 'pop_16', 'dpt16', 'bcg16', 'mea16', 'polio16','ipv16', 
        'pcv16', 'hpv16', 'dpt_droprate16', 'pentapcv_gap16','score16'], axis=1)

In [122]:
x.to_csv("election21.csv", index=False)

In [123]:
x

,District,Reg. Voters,AMURIAT OBOI PATRICK,KABULETA KIIZA JOSEPH,KALEMBE NANCY LINDA,KATUMBA JOHN,KYAGULANYI SSENTAMU ROBERT,MAO NORBERT,MAYAMBALA WILLY,MUGISHA MUNTU GREGG,MWESIGYE FRED,TUMUKUNDE HENRY KAKURUGU,YOWERI MUSEVENI TIBUHABUR WA KAGUTA,Valid Votes
0,ABIM,36539,433,71,66,179,3956,395,35,63,41,95,18254,23588
1,ADJUMANI,79364,1179,710,325,198,7866,225,81,264,183,265,35125,46421
2,AGAGO,98354,1595,337,299,202,10559,1834,243,407,356,433,47696,63961
3,ALEBTONG,115804,1920,604,425,297,16794,446,419,634,389,860,42832,65620
4,AMOLATAR,71173,3349,218,240,260,7185,206,134,310,289,466,38619,51276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,SOROTI,92720,19758,505,491,469,5196,184,166,298,324,338,34590,62319
108,TORORO,268434,8876,881,682,521,54556,561,143,657,485,893,86248,154503
109,WAKISO,1154857,3730,772,753,2520,425002,1101,140,2764,529,1684,122505,561500
110,YUMBE,113855,1129,368,371,181,16890,265,129,304,299,528,50686,71150
111,ZOMBO,123432,1260,421,434,310,9111,1176,207,498,305,606,45578,59906

In [124]:
x.columns = ['Dsitrict', 'RegVoters', 'AMURIAT','KABULETA', 'KALEMBE', 'KATUMBA', 'KYAGULANYI', 'MAO', 'MAYAMBALA', 'MUNTU', 'MWESIGYE', 'TUMUKUNDE', 'TIBUHABURWA', 'Valid Votes']

In [125]:
x.columns

Index(['Dsitrict', 'RegVoters', 'AMURIAT', 'KABULETA', 'KALEMBE', 'KATUMBA',
       'KYAGULANYI', 'MAO', 'MAYAMBALA', 'MUNTU', 'MWESIGYE', 'TUMUKUNDE',
       'TIBUHABURWA', 'Valid Votes'],
      dtype='object')

In [126]:
x

,Dsitrict,RegVoters,AMURIAT,KABULETA,KALEMBE,KATUMBA,KYAGULANYI,MAO,MAYAMBALA,MUNTU,MWESIGYE,TUMUKUNDE,TIBUHABURWA,Valid Votes
0,ABIM,36539,433,71,66,179,3956,395,35,63,41,95,18254,23588
1,ADJUMANI,79364,1179,710,325,198,7866,225,81,264,183,265,35125,46421
2,AGAGO,98354,1595,337,299,202,10559,1834,243,407,356,433,47696,63961
3,ALEBTONG,115804,1920,604,425,297,16794,446,419,634,389,860,42832,65620
4,AMOLATAR,71173,3349,218,240,260,7185,206,134,310,289,466,38619,51276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,SOROTI,92720,19758,505,491,469,5196,184,166,298,324,338,34590,62319
108,TORORO,268434,8876,881,682,521,54556,561,143,657,485,893,86248,154503
109,WAKISO,1154857,3730,772,753,2520,425002,1101,140,2764,529,1684,122505,561500
110,YUMBE,113855,1129,368,371,181,16890,265,129,304,299,528,50686,71150
111,ZOMBO,123432,1260,421,434,310,9111,1176,207,498,305,606,45578,59906

In [130]:
x = x.rename(columns={'Valid Votes': "ValidVotes"})

In [131]:
x

,Dsitrict,RegVoters,AMURIAT,KABULETA,KALEMBE,KATUMBA,KYAGULANYI,MAO,MAYAMBALA,MUNTU,MWESIGYE,TUMUKUNDE,TIBUHABURWA,ValidVotes
0,ABIM,36539,433,71,66,179,3956,395,35,63,41,95,18254,23588
1,ADJUMANI,79364,1179,710,325,198,7866,225,81,264,183,265,35125,46421
2,AGAGO,98354,1595,337,299,202,10559,1834,243,407,356,433,47696,63961
3,ALEBTONG,115804,1920,604,425,297,16794,446,419,634,389,860,42832,65620
4,AMOLATAR,71173,3349,218,240,260,7185,206,134,310,289,466,38619,51276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,SOROTI,92720,19758,505,491,469,5196,184,166,298,324,338,34590,62319
108,TORORO,268434,8876,881,682,521,54556,561,143,657,485,893,86248,154503
109,WAKISO,1154857,3730,772,753,2520,425002,1101,140,2764,529,1684,122505,561500
110,YUMBE,113855,1129,368,371,181,16890,265,129,304,299,528,50686,71150
111,ZOMBO,123432,1260,421,434,310,9111,1176,207,498,305,606,45578,59906

In [132]:
x.columns

Index(['Dsitrict', 'RegVoters', 'AMURIAT', 'KABULETA', 'KALEMBE', 'KATUMBA',
       'KYAGULANYI', 'MAO', 'MAYAMBALA', 'MUNTU', 'MWESIGYE', 'TUMUKUNDE',
       'TIBUHABURWA', 'ValidVotes'],
      dtype='object')

In [133]:
x = x.drop(['RegVoters'], axis=1)

In [134]:
x

,Dsitrict,AMURIAT,KABULETA,KALEMBE,KATUMBA,KYAGULANYI,MAO,MAYAMBALA,MUNTU,MWESIGYE,TUMUKUNDE,TIBUHABURWA,ValidVotes
0,ABIM,433,71,66,179,3956,395,35,63,41,95,18254,23588
1,ADJUMANI,1179,710,325,198,7866,225,81,264,183,265,35125,46421
2,AGAGO,1595,337,299,202,10559,1834,243,407,356,433,47696,63961
3,ALEBTONG,1920,604,425,297,16794,446,419,634,389,860,42832,65620
4,AMOLATAR,3349,218,240,260,7185,206,134,310,289,466,38619,51276
...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,SOROTI,19758,505,491,469,5196,184,166,298,324,338,34590,62319
108,TORORO,8876,881,682,521,54556,561,143,657,485,893,86248,154503
109,WAKISO,3730,772,753,2520,425002,1101,140,2764,529,1684,122505,561500
110,YUMBE,1129,368,371,181,16890,265,129,304,299,528,50686,71150
111,ZOMBO,1260,421,434,310,9111,1176,207,498,305,606,45578,59906

In [139]:
x = x.rename(columns={'District': "district"})

In [143]:
x.to_csv("election21.csv")

In [2]:
y = pd.read_csv('data/election21.csv')

In [3]:
y

,id,district,AMURIAT,KABULETA,KALEMBE,KATUMBA,KYAGULANYI,MAO,MAYAMBALA,MUNTU,MWESIGYE,TUMUKUNDE,TIBUHABURWA,ValidVotes
0,1,ABIM,433,71,66,179,3956,395,35,63,41,95,18254,23588
1,2,ADJUMANI,1179,710,325,198,7866,225,81,264,183,265,35125,46421
2,3,AGAGO,1595,337,299,202,10559,1834,243,407,356,433,47696,63961
3,4,ALEBTONG,1920,604,425,297,16794,446,419,634,389,860,42832,65620
4,5,AMOLATAR,3349,218,240,260,7185,206,134,310,289,466,38619,51276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,108,SOROTI,19758,505,491,469,5196,184,166,298,324,338,34590,62319
108,109,TORORO,8876,881,682,521,54556,561,143,657,485,893,86248,154503
109,110,WAKISO,3730,772,753,2520,425002,1101,140,2764,529,1684,122505,561500
110,111,YUMBE,1129,368,371,181,16890,265,129,304,299,528,50686,71150
111,112,ZOMBO,1260,421,434,310,9111,1176,207,498,305,606,45578,59906

In [8]:
y.to_csv("ugmap/data/ug21.csv", index=False)

In [11]:
len(y)

112

In [14]:
asd = []
for i in range(112):
    asd.append( y['district'][i] )

In [15]:
asd

['ABIM',
 'ADJUMANI',
 'AGAGO',
 'ALEBTONG',
 'AMOLATAR',
 'AMUDAT',
 'AMURIA',
 'AMURU',
 'APAC',
 'ARUA',
 'BUDAKA',
 'BUDUDA',
 'BUGIRI',
 'BUHWEJU',
 'BUIKWE',
 'BUKEDEA',
 'BUKOMANSIMBI',
 'BUKWO',
 'BULAMBULI',
 'BULIISA',
 'BUNDIBUGYO',
 'BUSHENYI',
 'BUSIA',
 'BUTALEJA',
 'BUTAMBALA',
 'BUVUMA',
 'BUYENDE',
 'DOKOLO',
 'GOMBA',
 'GULU',
 'HOIMA',
 'IBANDA',
 'IGANGA',
 'ISINGIRO',
 'JINJA',
 'KAABONG',
 'KABALE',
 'KABAROLE',
 'KABERAMAIDO',
 'KALANGALA',
 'KALIRO',
 'KALUNGU',
 'KAMPALA',
 'KAMULI',
 'KAMWENGE',
 'KANUNGU',
 'KAPCHORWA',
 'KASESE',
 'KATAKWI',
 'KAYUNGA',
 'KIBAALE',
 'KIBOGA',
 'KIBUKU',
 'KIRUHURA',
 'KIRYANDONGO',
 'KISORO',
 'KITGUM',
 'KOBOKO',
 'KOLE',
 'KOTIDO',
 'KUMI',
 'KWEEN',
 'KYANKWANZI',
 'KYEGEGWA',
 'KYENJOJO',
 'LAMWO',
 'LIRA',
 'LUUKA',
 'LUWERO',
 'LWENGO',
 'LYANTONDE',
 'MANAFWA',
 'MARACHA',
 'MASAKA',
 'MASINDI',
 'MAYUGE',
 'MBALE',
 'MBARARA',
 'MITOOMA',
 'MITYANA',
 'MOROTO',
 'MOYO',
 'MPIGI',
 'MUBENDE',
 'MUKONO',
 'NAKAPIRIPIRIT',
 'NAKASEKE',
 'NAKASONGOLA',
 'NAMAYINGO',
 'NAMUTUMBA',
 'NAPAK',
 'NEBBI',
 'NGORA',
 'NTOROKO',
 'NTUNGAMO',
 'NWOYA',
 'OTUKE',
 'OYAM',
 'PADER',
 'PALLISA',
 'RAKAI',
 'RUBIRIZI',
 'RUKUNGIRI',
 'SSEMBABULE',
 'SERERE',
 'SHEEMA',
 'SIRONKO',
 'SOROTI',
 'TORORO',
 'WAKISO',
 'YUMBE',
 'ZOMBO']